# Generated by Django 5.0.7 on 2025-08-08 11:58

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Film title', max_length=200)),
                ('slug', models.SlugField(max_length=210, unique_for_date='created_on')),
                ('film_title', models.CharField(help_text='Original film title', max_length=200)),
                ('year', models.IntegerField(help_text='Release year')),
                ('director', models.CharField(help_text='Film director', max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3, help_text='Your rating (1-5 stars)')),
                ('body', models.TextField(help_text='Your review')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horror_reviews', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text="Tags like 'slasher', 'psychological', 'gore', etc.", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.review'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-updated_on'], name='blog_review_updated_e08c44_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='blog_review_rating_3336e7_idx'),
        ),
        migrations.DeleteModel(
            name='POST',
        ),
    ]
